[default]
LOG_FILE_NAME='st_logger'
LOG_LEVEL = 'INFO'
LOG_FORMAT = '[%(asctime)s] [%(levelname)s] [%(message)s] [--> %(pathname)s [%(process)d]:]'
LOG_FILE_LOCATION = '/tmp/'
POSTGRES_SERVER_DRIVER = "org.postgresql.Driver"
CONNECTOR='{"Oracle":"OracleConnector", "Snowflake":"SnowflakeConnector", "Postgres":"PostgresConnector", "MySql":"MySQLConnector"}'

[production]


[development]
